@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    ArrowMessageAlignment center
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    BoxBorderColor Black
}

skinparam Collections {
    BorderColor Black
    BackgroundColor White
}

skinparam control{
    BorderColor Black
    BackgroundColor White
}
control GameController
participant TFTdriver
GameController-->TFTdriver : DrawGame(Pipepair* pipes, int numPillars, FlappyObject* flappy, int speed)
activate TFTdriver
loop numPillars
    TFTdriver-->TFTdriver : FillRectangle(upperPipe coordinates, color)
    TFTdriver-->TFTdriver : FillRectangle(lowerPipe coordinates, color)
end
TFTdriver-->TFTdriver : DrawFlappy(Flappy coordinates, color)
deactivate TFTdriver
@enduml