@startuml
control GameController
boundary TFTDriver
--> GameController : NextFrame(bool screenPressed)
GameController -> GameController : DetectCollision()
opt Collision detected
    GameController -> GameController : GameOver()
    <-- GameController: Return 
end
GameController -> TFTDriver : EraseObjects(PipePair * pipes,\n int numPipePairs, \n FlappyObject * flappy,\n unsigned int BackgroundColor, \n int speed)
GameController -> GameController : UpdatePipes()
GameController -> GameController : UpdateFlappy(screenPressed);
GameController -> GameController : CheckIncrementScore()
opt Increment score
GameController -> GameController : score++
GameController -> TFTDriver : UpdateScore(score)
end
GameController -> TFTDriver : DrawGame(PipePair * pipes, \n int numPipePairs,\n FlappyObject * flappy,\n int speed)
@enduml