@startuml
actor Gamer
boundary XPT2046
participant TouchDriver << (C,#ADD1B2) Driver >>
participant INT4 << MAIN >>


Gamer --> XPT2046 : Touches screen
XPT2046 --> INT4 : Sends interrupts signal on INT4 pin
@enduml