@startuml
skinparam sequence {
    ArrowColor Black
    ActorBorderColor Black
    LifeLineBorderColor Black
    ArrowMessageAlignment center
    ParticipantBorderColor Black
    ParticipantBackgroundColor White
    BoxBorderColor Black
}

skinparam activity {
    BorderColor Black
    BackgroundColor White
}
(*) --> "Chip select low"
if "Screen Touched" then
    -->[true] "Write Data (y)"
    --> "Read Data (y)"
    if "Screen touched" then
        -->[true] "Write Data (x)"
        --> "Read Data (x)"
        --> "Update Position"
        --> "Chip select high"
    else
        -->[false] "Chip select high"
        --> "Cycle"
    endif
else
    -->[false] "Chip select high"   
endif
@enduml